### ISSUE TITLE
Compilation failed for Ubuntu X64 but succeed with modification to neo/sound/sound.h

### ISSUE THREAD

**Issue by bhree** [eXistence/fhDOOM#15]
At the first attempt to build, error happened complaining incomplete structure of struct EFXEAXREVERBPROPERTIES. Change line 129 ,
from :
>struct EFXEAXREVERBPROPERTIES;

to :

>struct EFXEAXREVERBPROPERTIES {
	float 	flAirAbsorptionGainHF;
	float 	flDecayHFRatio;
 	float 	flDecayLFRatio;
 	float 	flDecayTime;
 	float 	flDensity;
 	float 	flDiffusion;
 	float 	flEchoDepth;
 	float 	flEchoTime;
 	float 	flGain;
 	float 	flGainHF;
 	float 	flGainLF;
 	float 	flHFReference;
 	float 	flLateReverbDelay;
 	float 	flLateReverbGain;
 	float 	flLateReverbPan [3];
 	float 	flLFReference;
 	float 	flModulationDepth;
 	float 	flModulationTime;
 	float 	flReflectionsDelay;
 	float 	flReflectionsGain;
 	float 	flReflectionsPan [3];
 	float 	flRoomRolloffFactor;
 	int 	iDecayHFLimit;
};

and compilation can continue and the binary is playable. I don't know wether this is only affecting my system or can affect wider audience. I don't know either wether the change is necessary. My system is Ubuntu x64 with modest hardware of Intel Compute stick Atom X5-8300 1,6GHz, 2GB RAM and Intel HD graphics. Compiled using gcc|release option.

**Comment by hogsy** [comment]
This was fixed already, so I think this can be closed.
