### ISSUE TITLE
keycard fallen through table

### ISSUE THREAD

**Issue by MamiyaOtaru** [eXistence/fhDOOM#22]
level 3 Mars City (revisited) the security keycard in the Reception Processing room has fallen through the table and can't be picked up.  Happens every time I play the level in fhdoom, and not in the original engine.  Makes it impossible to advance

![keycard](https://user-images.githubusercontent.com/2042826/55679053-7d8f8180-58c1-11e9-87e5-abe663f2f38e.jpg)

**Comment by ManoaNosea** [comment]
lel xD

**Comment by MamiyaOtaru** [comment]
Not your bug.  Happens with the Redux mod and fhDoom.  Also happens with Redux and dhewm3.  Does not happen with dhewm3 or fhDoom without Redux,  BUT also does not happen with Redux and vanilla, which is why I assumed the bug was in fhDoom (sorry).  

Fix (in Redux) in items.def setting the key items to 
	"spawnclass"					"idItem"
instead of 
	"spawnclass"					"idMoveableItem"

I am curious why that breaks the keycard fhDoom and dhewm3 but not vanilla.  You may take a look at that jsut for mod compatibility reasons, but as it is introduced via another bug, this one should obviously be closed.
