### ISSUE TITLE
Black screen on vid_restart, reloadengine, and mod load

### ISSUE THREAD

**Issue by Kerfuffles** [eXistence/fhDOOM#4]
Restarting the video subsystem, loading a mod, or restarting the entire engine causes a black screen that doesn't recover. However, the game can be heard and operated normally during this state (entering console commands, actually playing the game) until a visual event happens (imp throws a fireball), in which windows spits out "_fhDoom has stopped working_" and closes it.

Steps to recreate state after mod loading:
**1.** Load game to menu
**2.** Press mods and load a mod (even just a simple mod with no content)
**3.** Wait for mod to load

After this the game enters a black screen state that will not recover.

Steps to recreate state after vid_restart:
**1.** Load game to menu
**2.** Open console with ~
**3.** Type and submit the vid_restart command

Same as previous.

Repeat the same thing for reloadengine.

I have additionally tried the old method of loading mods by shortcut using +fs_game modname, but doom gives me the "_fs_game is write protected_" error and doesn't do anything. Opposite of what is normally expected.

This issue basically forces me to mod the base game files, which is less than ideal.

**Comment by eXistence** [comment]
i will look into it, thx for reporting :)

**Comment by Kerfuffles** [comment]
Any news?

**Comment by eXistence** [comment]
Its already fixed for the most part. I originally wanted to release it together with a bunch of other stuff in the next release. Unfortunately some issues with that other stuff came up and the whole thing takes longer than expected. 
I might release a bugfix-only version soon, just to get it out.

**Comment by moozhub** [comment]
Anything new one that patched build? I'm experiencing this issue as well.

**Comment by eXistence** [comment]
shame on me, a new release is long overdue :(
I am working on a couple of last bug fixes right now and i will hopefully release a new version this weekend.

**Comment by eXistence** [comment]
status update: some linux issues need to be fixed. I hope to get them fixed today or tomorrow

**Comment by eXistence** [comment]
i just released a new version: http://www.facinghell.com/fhdoom/fhDOOM-1.5.2-1414.zip
the issues with vid_restart and mod loading should be solved. I can easily switch between the original game and the expansion pack RoE and a test mod via GUI (tested on Windows and Linux).

You can't change fs_game after the game started, but this should work:
fhDOOM.exe +set fs_game mymod

This release contains mostly bugfixes, i will post a more complete list of changes tomorrow.

**Comment by moozhub** [comment]
Thanks so much! I'll test it when I can...thanks for the update

**Comment by Kerfuffles** [comment]
Awesome. I'll give it a test within the next week. Thanks!
