### ISSUE TITLE
Linux - errors on compilation

### ISSUE THREAD

**Issue by volumetricsteve** [eXistence/fhDOOM#5]
Hello,

As described in the "Building on Linux" issue, I was getting errors about intptr_t and Class.h

I fixed this by adding:

#include <stdint.h>

to the beginning of Class.h

Apparently implementations, of intptr_t vary based on your environment or compiler, so sometimes it's implied, sometimes it's not, I'm guessing it's implied with the Microsoft stuff, but not with GCC 6.3

Either way, I've gotten past that now - just letting you know what fixed that particular issue.

Cheers

**Comment by BielBdeLuna** [comment]
you would be far better if you add a pull request

**Comment by volumetricsteve** [comment]
Github makes zero sense to me.  I'll try to figure it out......I guess.

**Comment by BielBdeLuna** [comment]
if you make the change in the file you just press pull request (in order to save your changes) and you're set

**Comment by eXistence** [comment]
I am on vacation next week, so i can't look into the issue right now, but i will do so as soon as i am back.

**Comment by volumetricsteve** [comment]
I think I made the pull request work...The videos I saw on google for what to do in -no way- resembled the perfectly straight forward thing you suggested, BielBdeLuna.  Either way, hopefully when eXistence gets back he can do it the way he wants.

**Comment by BielBdeLuna** [comment]
perfect!

**Comment by eXistence** [comment]
fixed missing header (see pull request), thx for reporting :)
