### ISSUE TITLE
Linux - error: 'next' was not declared in this scope

### ISSUE THREAD

**Issue by volumetricsteve** [eXistence/fhDOOM#6]
After having fixed an issue with intptr_t, Upon compiling I'm now running into this error:

```
[ 11%] Building CXX object neo/game/CMakeFiles/fhGame-x86.dir/ai/AI_pathing.cpp.o
/ramdisk/fhDOOM-master/neo/game/ai/AI_pathing.cpp: In function 'pathNode_t* BuildPathTree(const obstacle_t*, int, const idBounds&, const idVec2&, const idVec2&, obstaclePath_t&)':
/ramdisk/fhDOOM-master/neo/game/ai/AI_pathing.cpp:597:52: error: 'next' was not declared in this scope
  idQueueTemplate<pathNode_t, offsetof( pathNode_t, next ) > pathNodeQueue, treeQueue;

```

Google suggests:

https://stackoverflow.com/questions/24416857/c-error-function-was-not-declared-in-this-scope

I'm still looking into this but hopefully there's some flag I can pass to GCC to make it happy with non-scope declaration, probably another thing that Microsoft is cool with but GCC doesn't like.

**Comment by eXistence** [comment]
fixed missing header, thx for reporting :)
